create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  status text not null default 'checkout_pending'
    check (status in (
      'checkout_pending',
      'checkout_created',
      'paid',
      'payment_failed',
      'expired',
      'payment_review',
      'cancelled'
    )),
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid', 'paid', 'processing', 'failed')),
  fulfillment_status text not null default 'not_started'
    check (fulfillment_status in (
      'not_started',
      'pending',
      'draft_created',
      'submitted',
      'failed',
      'fulfilled'
    )),
  currency text not null default 'usd'
    check (currency ~ '^[a-z]{3}$'),
  subtotal_cents bigint not null default 0 check (subtotal_cents >= 0),
  shipping_cents bigint not null default 0 check (shipping_cents >= 0),
  tax_cents bigint not null default 0 check (tax_cents >= 0),
  total_cents bigint not null default 0 check (total_cents >= 0),
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text unique,
  stripe_customer_id text,
  customer_email text,
  customer_name text,
  customer_phone text,
  shipping_address jsonb,
  printful_order_id text unique,
  printful_external_id text unique,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id),
  product_variant_id uuid references public.product_variants(id),
  storefront_product_id text not null,
  storefront_variant_id text not null,
  printful_sync_product_id bigint,
  printful_sync_variant_id bigint,
  printful_catalog_variant_id bigint,
  product_name text not null,
  variant_name text,
  color text,
  size text,
  sku text,
  unit_amount_cents bigint not null check (unit_amount_cents >= 0),
  quantity integer not null check (quantity > 0),
  line_total_cents bigint not null check (line_total_cents >= 0),
  image_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.stripe_webhook_events (
  id uuid primary key default gen_random_uuid(),
  stripe_event_id text unique not null,
  event_type text not null,
  livemode boolean not null,
  status text not null default 'received'
    check (status in ('received', 'processing', 'processed', 'ignored', 'failed')),
  checkout_session_id text,
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create index orders_status_idx on public.orders (status);
create index orders_payment_status_idx on public.orders (payment_status);
create index orders_created_at_idx on public.orders (created_at);
-- Unique constraints above provide indexes for both Stripe identifiers.

create index order_items_order_id_idx on public.order_items (order_id);
create index order_items_product_variant_id_idx
  on public.order_items (product_variant_id);
create index order_items_printful_sync_variant_id_idx
  on public.order_items (printful_sync_variant_id);

create index stripe_webhook_events_event_type_idx
  on public.stripe_webhook_events (event_type);
create index stripe_webhook_events_status_idx
  on public.stripe_webhook_events (status);
create index stripe_webhook_events_received_at_idx
  on public.stripe_webhook_events (received_at);

create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.stripe_webhook_events enable row level security;

revoke all on table public.orders from anon, authenticated;
revoke all on table public.order_items from anon, authenticated;
revoke all on table public.stripe_webhook_events from anon, authenticated;

grant select, insert, update, delete on table public.orders to service_role;
-- Purchase snapshots may be inserted and read, but never updated in place.
grant select, insert on table public.order_items to service_role;
grant all on table public.stripe_webhook_events to service_role;
grant usage, select on sequence public.orders_order_number_seq to service_role;

-- No public RLS policies are intentionally defined for these server-only tables.
